Controllers/UserRegistrationController.cs
using FinalProject.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Web.UI;
using FinalProject.Repository;

namespace FinalProject.Controllers
{
    public class UserRegistrationController : Controller
    {
        // GET: NewReg
        public ActionResult Index()
        {
            return View();
        }



        // Post: NewReg
        [HttpPost]
        public ActionResult Index(UserClass uc, HttpPostedFileBase file)
        {
            string mainconn = ConfigurationManager.ConnectionStrings["MyConnection"].ConnectionString;
            SqlConnection sqlconn = new SqlConnection(mainconn);

            SqlCommand sqlCommand = new SqlCommand("sp_InsertUserReg", sqlconn);
            sqlCommand.CommandType = CommandType.StoredProcedure;

            sqlCommand.Parameters.AddWithValue("@FirstName", uc.FirstName);
            sqlCommand.Parameters.AddWithValue("@LastName", uc.LastName);
            sqlCommand.Parameters.AddWithValue("@DateOfBirth", uc.DateOfBirth);
            sqlCommand.Parameters.AddWithValue("@Gender", uc.Gender);
            sqlCommand.Parameters.AddWithValue("@PhoneNumber", uc.PhoneNumber);
            sqlCommand.Parameters.AddWithValue("@EmailAddress", uc.EmailAddress);
            sqlCommand.Parameters.AddWithValue("@Address", uc.Address);
            sqlCommand.Parameters.AddWithValue("@Country", uc.Country);
            sqlCommand.Parameters.AddWithValue("@State", uc.State);
            sqlCommand.Parameters.AddWithValue("@City", uc.City);
            sqlCommand.Parameters.AddWithValue("@Postcode", uc.Postcode);
            sqlCommand.Parameters.AddWithValue("@PassportNumber", uc.PassportNumber);
            sqlCommand.Parameters.AddWithValue("@AdharNumber", uc.AdharNumber);
            sqlCommand.Parameters.AddWithValue("@Username", uc.Username);
            sqlCommand.Parameters.AddWithValue("@Password", uc.Password);
            

            if (file != null && file.ContentLength > 0)
            {

                string filename = Path.GetFileName(file.FileName);
                string imgpath = Path.Combine(Server.MapPath("/User-Images/"), filename);
                file.SaveAs(imgpath);
                sqlCommand.Parameters.AddWithValue("@Photo", "/User-Images/" + filename);
            }
            else
            {
                sqlCommand.Parameters.AddWithValue("@Photo", DBNull.Value);
            }
            sqlconn.Open();
            sqlCommand.ExecuteNonQuery();
            sqlconn.Close();

            ViewData["Message"] = "User Record " + uc.FirstName + " Is Saved Successfully!";
            return View();


        }


        


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar-logo {
            width: 100px;
            height: auto; 
        }
    </style>
    
</head>
<body style="background-color: #D8F9F9">

    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                <a href="@Url.Action("Index", "Home", new { area = "" })" class="navbar-brand">
                    <img src="https://www.cgiguangzhou.gov.in/docs/1507963852_download.jpg" alt="Logo" class="navbar-logo">
                </a>

                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    @if (Session["EmailAddress"] == null)
                    {
                        <ul class="navbar-nav flex-grow-1 mr-auto">

                            <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                        </ul>
                    }
                </div>

                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" style="margin-right:0px">
                    @if (Session["EmailAddress"] == null)
                    {
                        <ul class="navbar-nav flex-grow-1">

                            <li>@Html.ActionLink("Sign up", "Index", "UserRegistration", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Sign in", "Index", "UserLogin", new { area = "" }, new { @class = "nav-link" })</li>

                            <li>@Html.ActionLink("Admin_Sign in", "Index", "AdminLogin", new { area = "" }, new { @class = "nav-link" })</li>
                        </ul>
                    }
                    else if (Session["EmailAddress"].ToString() == "admin1@gmail.com")
                    {
                        <ul class="navbar-nav flex-grow-1 a">
                            @{
                                string user = Session["EmailAddress"].ToString();
                            }


                            <li>@Html.ActionLink("Welcome Admin", "adminwelcome", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("View user", "UsersView", "Admin", new { area = "" }, new { @class = "nav-link" })</li>


                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">

                            @{
                                string user = Session["EmailAddress"].ToString();
                            }


                            <li>@Html.ActionLink("Update details", "UpdateUser", "Login", new { area = "" }, new { @class = "nav-link" })</li>

                        </ul>
                    }

                </div>


            </div>
        </nav>
    </header>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutPageAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar-logo {
            width: 100px;
            height: auto;
        }
    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="@Url.Content("/Content/NavBar.css")" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"></script>
</head>
<body style="background-color: #D8F9F9">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <a href="@Url.Action("AdminHome", "AdminLogin", new { area = "" })" class="navbar-brand">
                <img src="https://www.cgiguangzhou.gov.in/docs/1507963852_download.jpg" alt="Logo" class="navbar-logo">
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">

                    <li>@Html.ActionLink("Home", "AdminHome", "AdminLogin", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Admin profile", "AdminWelcome", "AdminLogin", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("User Details", "UsersView", "AdminLogin", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("visa Applications", "ApplicantsView", "AdminLogin", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>

    <div>
        @RenderBody()

        <hr />
        

                <!-- Footer -->
        <footer class=" text-center text-dark">
            <!-- Grid container -->
            <div class="container p-4 footerayshel">
                <!-- Section: Social media -->
                <section class="mb-4">
                    <!-- Facebook -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="#!" role="button">
                        <i class="fab fa-facebook"></i>
                    </a>


                    <!-- Google -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="https://www.justdial.com/Malappuram/Ayshel-Boutique-Near-Musjid-Mangalam-Mlp/9999PX483-X483-190322202629-T6N6_BZDET" role="button">
                        <i class="fab fa-google"></i>
                    </a>

                    <!-- Instagram -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="https://www.instagram.com/ayshellshop/?hl=en" role="button">
                        <i class="fab fa-instagram"></i>
                    </a>

                    <!-- Linkedin -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="#!" role="button">
                        <i class="fab fa-linkedin-in"></i>
                    </a>


                    <!-- Section: Social media -->
                    <!-- Section: Text -->
                    <section class="mb-4">
                        <p>
                            Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.
                        </p>
                    </section>
                    <!-- Section: Text -->
                    <!-- Copyright -->
                    <div class="footerayshel">
                        <div class="text-center p-3 " style="background-color: rgba(0, 0, 0, 0.2);">
                            © 2020 Copyright:
                            <a class="text-dark" href="https://mdbootstrap.com/">E-Visa.com</a>
                        </div>
                    </div>

            </div>

        </footer>

        </div>





                
        
   



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutPageUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar-logo {
            width: 100px;
            height: auto;
        }
    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="@Url.Content("/Content/NavBar.css")" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"></script>
</head>
<body style="background-color: #D8F9F9">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                <a href="@Url.Action("AdminHome", "AdminLogin", new { area = "" })" class="navbar-brand">
                    <img src="https://www.cgiguangzhou.gov.in/docs/1507963852_download.jpg" alt="Logo" class="navbar-logo">
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Home", "UserHome", "UserLogin", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("User profile", "Welcome", "UserLogin", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Edit profile", "UpdateUser", "UserLogin", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Apply for visa", "VisaApplication", "UserLogin", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Check status", "CheckStatus", "UserLogin", new { area = "" }, new { @class = "nav-link" })</li>



                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <!-- Footer -->
        <footer class=" text-center text-dark">
            <!-- Grid container -->
            <div class="container p-4 footerayshel">
                <!-- Section: Social media -->
                <section class="mb-4">
                    <!-- Facebook -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="#!" role="button">
                        <i class="fab fa-facebook"></i>
                    </a>


                    <!-- Google -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="https://www.justdial.com/Malappuram/Ayshel-Boutique-Near-Musjid-Mangalam-Mlp/9999PX483-X483-190322202629-T6N6_BZDET" role="button">
                        <i class="fab fa-google"></i>
                    </a>

                    <!-- Instagram -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="https://www.instagram.com/ayshellshop/?hl=en" role="button">
                        <i class="fab fa-instagram"></i>
                    </a>

                    <!-- Linkedin -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="#!" role="button">
                        <i class="fab fa-linkedin-in"></i>
                    </a>


                    <!-- Section: Social media -->
                    <!-- Section: Text -->
                    <section class="mb-4">
                        <p>
                            Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.
                        </p>
                    </section>
                    <!-- Section: Text -->
                    <!-- Copyright -->
                    <div class="footerayshel">
                        <div class="text-center p-3 " style="background-color: rgba(0, 0, 0, 0.2);">
                            © 2020 Copyright:
                            <a class="text-dark" href="https://mdbootstrap.com/">E-Visa.com</a>
                        </div>
                    </div>

            </div>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>